### ISSUE TITLE
Debug Message in Log?

### ISSUE THREAD

**Issue by suerion** [neptunecentury/time-lived#4]
I think you had not disabled the Debug Messages, could you add it to the Config file? i think it would be better if i could enable and disable it from config

https://mclo.gs/BOHrLLL#L7123 
![image](https://github.com/user-attachments/assets/a8f653c3-103d-432c-b1bf-6e9f5cc54f23)

**Comment by neptunecentury** [comment]
Heh, yep. I will remove it for next update!

**Comment by suerion** [comment]
Thanks, it is nit a problem, but i think it is a really good mod and gimmick for the players :)
